<?php
/**
 * ModelInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  Xrely\Client\Model
 * @author   xrely team
 * @link     https://www.xrely.com
 */

/**
 * XRELY
 *
 * API Documentation for XRELY platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@xrely.com
 * Generated by: https://www.xrely.com
 * version: 2.4.13-SNAPSHOT
 */

/**
 * Do not edit the class manually.
 */

namespace Xrely\Client\Model;

/**
 * Interface abstracting model access.
 *
 * @package Xrely\Client\Model
 * @author  xrely team
 */
interface ModelInterface
{
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName();

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes();

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats();

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     *
     * @return array
     */
    public static function attributeMap();

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters();

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters();

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array
     */
    public function listInvalidProperties();

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool
     */
    public function valid();
}
